#!/usr/bin/env python3
"""
obj_to_c.py — Convert a Wavefront OBJ file to a C vertex array for citro3d.

Each output vertex contains:
  float position[3]   (x, y, z)
  float color[3]      (r, g, b) — tint; use 1 1 1 with textures (default)
  float normal[3]     (nx, ny, nz) — per-vertex normals, computed if absent
  float uv[2]         (u, v) — texture coordinates; (0, 0) if OBJ has no UVs

Usage:
  python3 obj_to_c.py model.obj [r g b] > model.h

  r g b are optional floats in [0,1] for the vertex colour tint (default: 1 1 1)

The output header defines:
  vertex model_vertices[]
  int    model_vertex_count
"""

import sys
import math
import os


def normalize(v):
    length = math.sqrt(sum(c * c for c in v))
    if length < 1e-8:
        return (0.0, 0.0, 1.0)
    return tuple(c / length for c in v)


def cross(a, b):
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def face_normal(p0, p1, p2):
    return normalize(cross(sub(p1, p0), sub(p2, p0)))


def parse_obj(path):
    positions = []
    uvs = []
    normals = []
    triangles = []  # list of ((pi, ti, ni), (pi, ti, ni), (pi, ti, ni))

    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            tag = parts[0]

            if tag == 'v':
                positions.append(tuple(float(x) for x in parts[1:4]))

            elif tag == 'vt':
                uvs.append((float(parts[1]), float(parts[2])))

            elif tag == 'vn':
                normals.append(tuple(float(x) for x in parts[1:4]))

            elif tag == 'f':
                # Each token: v, v/vt, v/vt/vn, or v//vn (1-indexed)
                verts = []
                for tok in parts[1:]:
                    indices = tok.split('/')
                    pi = int(indices[0]) - 1
                    ti = int(indices[1]) - 1 if len(indices) > 1 and indices[1] else None
                    ni = int(indices[2]) - 1 if len(indices) > 2 and indices[2] else None
                    verts.append((pi, ti, ni))

                # Fan-triangulate polygon faces
                for i in range(1, len(verts) - 1):
                    triangles.append((verts[0], verts[i], verts[i + 1]))

    return positions, uvs, normals, triangles


def centre_and_scale(positions):
    """Translate to origin and scale to fit in a unit cube."""
    if not positions:
        return positions
    mins = [min(p[i] for p in positions) for i in range(3)]
    maxs = [max(p[i] for p in positions) for i in range(3)]
    centre = [(mins[i] + maxs[i]) / 2.0 for i in range(3)]
    extent = max(maxs[i] - mins[i] for i in range(3))
    scale = 1.0 / extent if extent > 1e-8 else 1.0
    return [tuple((p[i] - centre[i]) * scale for i in range(3)) for p in positions]


def build_vertices(positions, uvs, normals, triangles, colour):
    out = []
    fallback_uv = (0.0, 0.0)

    for (p0i, t0i, n0i), (p1i, t1i, n1i), (p2i, t2i, n2i) in triangles:
        p0, p1, p2 = positions[p0i], positions[p1i], positions[p2i]

        # Normals — prefer OBJ per-vertex normals, fall back to face normal
        fn = face_normal(p0, p1, p2)
        n0 = normalize(normals[n0i]) if (n0i is not None and n0i < len(normals)) else fn
        n1 = normalize(normals[n1i]) if (n1i is not None and n1i < len(normals)) else fn
        n2 = normalize(normals[n2i]) if (n2i is not None and n2i < len(normals)) else fn

        # UVs — use OBJ coords if present; OBJ V is flipped relative to GPU convention
        uv0 = (uvs[t0i][0], 1.0 - uvs[t0i][1]) if (t0i is not None and t0i < len(uvs)) else fallback_uv
        uv1 = (uvs[t1i][0], 1.0 - uvs[t1i][1]) if (t1i is not None and t1i < len(uvs)) else fallback_uv
        uv2 = (uvs[t2i][0], 1.0 - uvs[t2i][1]) if (t2i is not None and t2i < len(uvs)) else fallback_uv

        out.append((p0, colour, n0, uv0))
        out.append((p1, colour, n1, uv1))
        out.append((p2, colour, n2, uv2))
    return out


def emit_header(vertices, source_name):
    lines = []
    lines.append(f'// Auto-generated by obj_to_c.py from {os.path.basename(source_name)}')
    lines.append(f'// {len(vertices)} vertices ({len(vertices) // 3} triangles)')
    lines.append(f'#pragma once')
    lines.append('')
    lines.append('typedef struct {')
    lines.append('    float position[3];')
    lines.append('    float color[3];')
    lines.append('    float normal[3];')
    lines.append('    float uv[2];')
    lines.append('} vertex;')
    lines.append('')
    lines.append(f'static const vertex model_vertices[] = {{')

    for (px, py, pz), (cr, cg, cb), (nx, ny, nz), (u, v) in vertices:
        lines.append(
            f'    {{ {{{px:.6f}f, {py:.6f}f, {pz:.6f}f}}, '
            f'{{{cr:.4f}f, {cg:.4f}f, {cb:.4f}f}}, '
            f'{{{nx:.6f}f, {ny:.6f}f, {nz:.6f}f}}, '
            f'{{{u:.6f}f, {v:.6f}f}} }},'
        )

    lines.append('};')
    lines.append('')
    lines.append(f'static const int model_vertex_count = {len(vertices)};')
    lines.append('')
    return '\n'.join(lines)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    obj_path = sys.argv[1]
    colour = (1.0, 1.0, 1.0)  # default white — use texture as-is
    if len(sys.argv) >= 5:
        colour = (float(sys.argv[2]), float(sys.argv[3]), float(sys.argv[4]))

    positions, uvs, normals, triangles = parse_obj(obj_path)
    if not triangles:
        print(f'error: no faces found in {obj_path}', file=sys.stderr)
        sys.exit(1)

    positions = centre_and_scale(positions)
    vertices = build_vertices(positions, uvs, normals, triangles, colour)

    has_uvs = any(t0i is not None for (_, t0i, _), _, _ in triangles)
    print(emit_header(vertices, obj_path), end='')
    print(f'// {len(triangles)} triangles from {obj_path} (UVs: {"yes" if has_uvs else "no"})', file=sys.stderr)


if __name__ == '__main__':
    main()
