#include <3ds.h>
#include <citro3d.h>
#include <tex3ds.h>
#include <string.h>
#include <math.h>
#include <stdio.h>
#include "vshader_shbin.h"
#include "model.h"  // generated by: python3 tools/obj_to_c.py <model.obj> > source/model.h

#define CLEAR_COLOR 0x68B0D8FF

#define DISPLAY_TRANSFER_FLAGS \
	(GX_TRANSFER_FLIP_VERT(0) | GX_TRANSFER_OUT_TILED(0) | GX_TRANSFER_RAW_COPY(0) | \
	GX_TRANSFER_IN_FORMAT(GX_TRANSFER_FMT_RGBA8) | GX_TRANSFER_OUT_FORMAT(GX_TRANSFER_FMT_RGB8) | \
	GX_TRANSFER_SCALING(GX_TRANSFER_SCALE_XY))

// Field of view, clip planes, and convergence depth (units matching model scale)
#define FOV         C3D_AngleFromDegrees(80.0f)
#define NEAR_PLANE  0.01f
#define FAR_PLANE   1000.0f
#define SCREEN_DEPTH 2.0f  // objects at this depth appear at the display surface

// Scale the 0–1 slider value to a sensible inter-ocular distance
#define IOD_SCALE   0.07f

static DVLB_s* vshader_dvlb;
static shaderProgram_s program;
static int uLoc_projection, uLoc_modelView;
static int uLoc_lightVec, uLoc_lightHalfVec, uLoc_lightClr, uLoc_material;
static C3D_Mtx material =
{
	{
	{ { 0.0f, 0.2f, 0.2f, 0.2f } }, // Ambient
	{ { 0.0f, 0.4f, 0.4f, 0.4f } }, // Diffuse
	{ { 0.0f, 0.8f, 0.8f, 0.8f } }, // Specular
	{ { 1.0f, 0.0f, 0.0f, 0.0f } }, // Emission
	}
};

// Camera defaults
#define CAM_Z_DEFAULT  -2.0f
#define CAM_X_DEFAULT   0.0f
#define CAM_Z_NEAR     -0.5f   // closest the camera can get (never reach origin)
#define CAM_Z_FAR     -10.0f   // furthest the camera can pull back
#define ZOOM_SPEED      0.025f // units per frame when D-Pad held
#define PAN_SPEED       0.015f // units per frame when D-Pad held
#define RESET_SPEED     0.15f  // lerp factor per frame during reset (ease-out)
#define RESET_EPSILON   0.001f // snap to target when this close

static void* vbo_data;
static C3D_Tex texDiffuse;
static C3D_Tex texNormal __attribute__((unused)); // reserved for normal map phase

// Accumulated rotation matrix — updated incrementally each frame so that
// circle pad deltas are always applied in screen space (arcball-style).
static C3D_Mtx modelRot;
static bool autoRotate = true;

static float camZ = CAM_Z_DEFAULT, camX = CAM_X_DEFAULT;
static bool  resetting = false;

static void sceneInit(void)
{
	// Load the vertex shader, create a shader program and bind it
	vshader_dvlb = DVLB_ParseFile((u32*)vshader_shbin, vshader_shbin_size);
	shaderProgramInit(&program);
	shaderProgramSetVsh(&program, &vshader_dvlb->DVLE[0]);
	C3D_BindProgram(&program);

	// Get the location of the uniforms
	uLoc_projection   = shaderInstanceGetUniformLocation(program.vertexShader, "projection");
	uLoc_modelView    = shaderInstanceGetUniformLocation(program.vertexShader, "modelView");
	uLoc_lightVec     = shaderInstanceGetUniformLocation(program.vertexShader, "lightVec");
	uLoc_lightHalfVec = shaderInstanceGetUniformLocation(program.vertexShader, "lightHalfVec");
	uLoc_lightClr     = shaderInstanceGetUniformLocation(program.vertexShader, "lightClr");
	uLoc_material     = shaderInstanceGetUniformLocation(program.vertexShader, "material");

	// Configure attributes: v0=position (3f), v1=color (3f), v2=normal (3f), v3=uv (2f)
	C3D_AttrInfo* attrInfo = C3D_GetAttrInfo();
	AttrInfo_Init(attrInfo);
	AttrInfo_AddLoader(attrInfo, 0, GPU_FLOAT, 3); // v0=position
	AttrInfo_AddLoader(attrInfo, 1, GPU_FLOAT, 3); // v1=color (tint)
	AttrInfo_AddLoader(attrInfo, 2, GPU_FLOAT, 3); // v2=normal
	AttrInfo_AddLoader(attrInfo, 3, GPU_FLOAT, 2); // v3=uv

	// Start with no rotation
	Mtx_Identity(&modelRot);

	// Create the VBO
	vbo_data = linearAlloc(sizeof(model_vertices));
	memcpy(vbo_data, model_vertices, sizeof(model_vertices));

	// Configure buffers
	C3D_BufInfo* bufInfo = C3D_GetBufInfo();
	BufInfo_Init(bufInfo);
	BufInfo_Add(bufInfo, vbo_data, sizeof(vertex), 4, 0x3210);

	// TexEnv stage 0: diffuse texture × Phong lighting (PRIMARY_COLOR from vertex shader)
	C3D_TexEnv* env = C3D_GetTexEnv(0);
	C3D_TexEnvInit(env);
	C3D_TexEnvSrc(env, C3D_Both, GPU_TEXTURE0, GPU_PRIMARY_COLOR, 0);
	C3D_TexEnvFunc(env, C3D_Both, GPU_MODULATE);

	// Load diffuse texture from romfs
	FILE* f = fopen("romfs:/gfx/cat_diffuse.t3x", "rb");
	if (f) {
		Tex3DS_Texture t3x = Tex3DS_TextureImportStdio(f, &texDiffuse, NULL, false);
		fclose(f);
		if (t3x) Tex3DS_TextureFree(t3x);
		C3D_TexSetFilter(&texDiffuse, GPU_LINEAR, GPU_LINEAR);
		C3D_TexSetWrap(&texDiffuse, GPU_REPEAT, GPU_REPEAT);
	}
}

// Projection is passed in so the same draw call works for both eyes
static void sceneRender(C3D_Mtx* proj)
{
	// Build modelView: apply accumulated screen-space rotation, then camera translation
	C3D_Mtx modelView;
	Mtx_Identity(&modelView);
	Mtx_Translate(&modelView, camX, 0.0f, camZ, true);
	Mtx_Multiply(&modelView, &modelView, &modelRot);

	// Update uniforms
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLoc_projection, proj);
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLoc_modelView,  &modelView);
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLoc_material,   &material);
	C3D_FVUnifSet(GPU_VERTEX_SHADER, uLoc_lightVec,     0.0f, 0.0f, -1.0f, 0.0f);
	C3D_FVUnifSet(GPU_VERTEX_SHADER, uLoc_lightHalfVec, 0.0f, 0.0f, -1.0f, 0.0f);
	C3D_FVUnifSet(GPU_VERTEX_SHADER, uLoc_lightClr,     1.0f, 1.0f,  1.0f, 1.0f);

	// Bind diffuse texture to unit 0 and draw
	C3D_TexBind(0, &texDiffuse);
	C3D_DrawArrays(GPU_TRIANGLES, 0, model_vertex_count);
}

static void sceneExit(void)
{
	C3D_TexDelete(&texDiffuse);
	linearFree(vbo_data);
	shaderProgramFree(&program);
	DVLB_Free(vshader_dvlb);
}

int main()
{
	// Mount the romfs so we can load textures
	romfsInit();

	// Initialize graphics — gfxSet3D enables the parallax barrier
	gfxInitDefault();
	gfxSet3D(true);
	C3D_Init(C3D_DEFAULT_CMDBUF_SIZE);

	// Two render targets at 2x resolution (480x800) — one per eye.
	// The transfer hardware downscales to 240x400, giving 4xSSAA on both eyes.
	C3D_RenderTarget* targetLeft  = C3D_RenderTargetCreate(480, 800, GPU_RB_RGBA8, GPU_RB_DEPTH24_STENCIL8);
	C3D_RenderTarget* targetRight = C3D_RenderTargetCreate(480, 800, GPU_RB_RGBA8, GPU_RB_DEPTH24_STENCIL8);
	C3D_RenderTargetSetOutput(targetLeft,  GFX_TOP, GFX_LEFT,  DISPLAY_TRANSFER_FLAGS);
	C3D_RenderTargetSetOutput(targetRight, GFX_TOP, GFX_RIGHT, DISPLAY_TRANSFER_FLAGS);

	sceneInit();

	while (aptMainLoop())
	{
		hidScanInput();

		u32 kDown = hidKeysDown();
		u32 kHeld = hidKeysHeld();

		if (kDown & KEY_START) break;
		if (kDown & KEY_L) autoRotate = !autoRotate;

		// R — snap rotation to identity and animate camera back to defaults
		if (kDown & KEY_R) {
			resetting = true;
			Mtx_Identity(&modelRot);
		}

		if (resetting) {
			// Ease-out lerp camera toward defaults — circle pad suspended during reset
			camZ += (CAM_Z_DEFAULT - camZ) * RESET_SPEED;
			camX += (CAM_X_DEFAULT - camX) * RESET_SPEED;

			if (fabsf(camZ - CAM_Z_DEFAULT) < RESET_EPSILON &&
			    fabsf(camX - CAM_X_DEFAULT) < RESET_EPSILON) {
				camZ = CAM_Z_DEFAULT; camX = CAM_X_DEFAULT;
				resetting = false;
			}
		} else {
			// Circle pad — build a screen-space delta rotation and pre-multiply
			// onto the accumulated rotation so axes never drift or couple
			circlePosition pos;
			hidCircleRead(&pos);

			// Z-axis roll: ZL = counter-clockwise, ZR = clockwise
			float rollDelta = 0.0f;
			if (kHeld & KEY_ZL) rollDelta =  0.02f;
			if (kHeld & KEY_ZR) rollDelta = -0.02f;

			// Deadzone — ignore small circle pad values caused by hardware drift
			#define DEADZONE 25
			if (pos.dx > -DEADZONE && pos.dx < DEADZONE) pos.dx = 0;
			if (pos.dy > -DEADZONE && pos.dy < DEADZONE) pos.dy = 0;

			// Auto-rotation kicks in only when the user isn't providing manual input
			bool manualInput = (pos.dx != 0 || pos.dy != 0 || rollDelta != 0.0f);
			float autoY = (autoRotate && !manualInput) ? 0.005f : 0.0f;

			if (manualInput || autoY != 0.0f) {
				C3D_Mtx delta;
				Mtx_Identity(&delta);
				Mtx_RotateY(&delta,  pos.dx * 0.0003f + autoY, true); // left/right + auto → screen Y axis
				Mtx_RotateX(&delta, -pos.dy * 0.0003f,         true); // up/down           → screen X axis
				Mtx_RotateZ(&delta,  rollDelta,                 true); // ZL/ZR             → screen Z axis
				Mtx_Multiply(&modelRot, &delta, &modelRot);
			}

			// D-Pad — zoom (up/down) and pan (left/right)
			if (kHeld & KEY_DUP)    camZ = camZ + ZOOM_SPEED < CAM_Z_NEAR ? camZ + ZOOM_SPEED : CAM_Z_NEAR;
			if (kHeld & KEY_DDOWN)  camZ = camZ - ZOOM_SPEED > CAM_Z_FAR  ? camZ - ZOOM_SPEED : CAM_Z_FAR;
			if (kHeld & KEY_DLEFT)  camX += PAN_SPEED;
			if (kHeld & KEY_DRIGHT) camX -= PAN_SPEED;
		}

		// Read the 3D slider and compute per-eye projections
		float iod = osGet3DSliderState() * IOD_SCALE;

		C3D_Mtx projLeft, projRight;
		if (iod > 0.0f) {
			// Stereo: offset each eye's projection by ±iod around the convergence plane
			Mtx_PerspStereoTilt(&projLeft,  FOV, C3D_AspectRatioTop, NEAR_PLANE, FAR_PLANE, -iod, SCREEN_DEPTH, false);
			Mtx_PerspStereoTilt(&projRight, FOV, C3D_AspectRatioTop, NEAR_PLANE, FAR_PLANE, +iod, SCREEN_DEPTH, false);
		} else {
			// Slider at zero — mono render into left eye only
			Mtx_PerspTilt(&projLeft, FOV, C3D_AspectRatioTop, NEAR_PLANE, FAR_PLANE, false);
		}

		C3D_FrameBegin(C3D_FRAME_SYNCDRAW);
			// Left eye (always rendered)
			C3D_RenderTargetClear(targetLeft, C3D_CLEAR_ALL, CLEAR_COLOR, 0);
			C3D_FrameDrawOn(targetLeft);
			sceneRender(&projLeft);

			// Right eye (only when slider is up)
			if (iod > 0.0f) {
				C3D_RenderTargetClear(targetRight, C3D_CLEAR_ALL, CLEAR_COLOR, 0);
				C3D_FrameDrawOn(targetRight);
				sceneRender(&projRight);
			}
		C3D_FrameEnd(0);
	}

	sceneExit();
	C3D_Fini();
	gfxExit();
	romfsExit();
	return 0;
}
