#include <3ds.h>
#include <citro3d.h>
#include <string.h>
#include <math.h>
#include "vshader_shbin.h"
#include "model.h"  // generated by: python3 tools/obj_to_c.py <model.obj> [r g b] > source/model.h

#define CLEAR_COLOR 0x68B0D8FF

#define DISPLAY_TRANSFER_FLAGS \
	(GX_TRANSFER_FLIP_VERT(0) | GX_TRANSFER_OUT_TILED(0) | GX_TRANSFER_RAW_COPY(0) | \
	GX_TRANSFER_IN_FORMAT(GX_TRANSFER_FMT_RGBA8) | GX_TRANSFER_OUT_FORMAT(GX_TRANSFER_FMT_RGB8) | \
	GX_TRANSFER_SCALING(GX_TRANSFER_SCALE_XY))

// Field of view, clip planes, and convergence depth (units matching model scale)
#define FOV         C3D_AngleFromDegrees(80.0f)
#define NEAR_PLANE  0.01f
#define FAR_PLANE   1000.0f
#define SCREEN_DEPTH 2.0f  // objects at this depth appear at the display surface

// Scale the 0–1 slider value to a sensible inter-ocular distance
#define IOD_SCALE   0.07f

static DVLB_s* vshader_dvlb;
static shaderProgram_s program;
static int uLoc_projection, uLoc_modelView;
static int uLoc_lightVec, uLoc_lightHalfVec, uLoc_lightClr, uLoc_material;
static C3D_Mtx material =
{
	{
	{ { 0.0f, 0.2f, 0.2f, 0.2f } }, // Ambient
	{ { 0.0f, 0.4f, 0.4f, 0.4f } }, // Diffuse
	{ { 0.0f, 0.8f, 0.8f, 0.8f } }, // Specular
	{ { 1.0f, 0.0f, 0.0f, 0.0f } }, // Emission
	}
};

// Camera defaults
#define CAM_Z_DEFAULT  -2.0f
#define CAM_X_DEFAULT   0.0f
#define CAM_Z_NEAR     -0.5f   // closest the camera can get (never reach origin)
#define CAM_Z_FAR     -10.0f   // furthest the camera can pull back
#define ZOOM_SPEED      0.025f // units per frame when D-Pad held
#define PAN_SPEED       0.015f // units per frame when D-Pad held
#define RESET_SPEED     0.15f  // lerp factor per frame during reset (ease-out)
#define RESET_EPSILON   0.001f // snap to target when this close

static void* vbo_data;
static float angleX = 0.0f, angleY = 0.0f;
static float camZ = CAM_Z_DEFAULT, camX = CAM_X_DEFAULT;
static bool  resetting = false;

static void sceneInit(void)
{
	// Load the vertex shader, create a shader program and bind it
	vshader_dvlb = DVLB_ParseFile((u32*)vshader_shbin, vshader_shbin_size);
	shaderProgramInit(&program);
	shaderProgramSetVsh(&program, &vshader_dvlb->DVLE[0]);
	C3D_BindProgram(&program);

	// Get the location of the uniforms
	uLoc_projection   = shaderInstanceGetUniformLocation(program.vertexShader, "projection");
	uLoc_modelView    = shaderInstanceGetUniformLocation(program.vertexShader, "modelView");
	uLoc_lightVec     = shaderInstanceGetUniformLocation(program.vertexShader, "lightVec");
	uLoc_lightHalfVec = shaderInstanceGetUniformLocation(program.vertexShader, "lightHalfVec");
	uLoc_lightClr     = shaderInstanceGetUniformLocation(program.vertexShader, "lightClr");
	uLoc_material     = shaderInstanceGetUniformLocation(program.vertexShader, "material");

	// Configure attributes: v0=position (3f), v1=color (3f), v2=normal (3f)
	C3D_AttrInfo* attrInfo = C3D_GetAttrInfo();
	AttrInfo_Init(attrInfo);
	AttrInfo_AddLoader(attrInfo, 0, GPU_FLOAT, 3); // v0=position
	AttrInfo_AddLoader(attrInfo, 1, GPU_FLOAT, 3); // v1=color
	AttrInfo_AddLoader(attrInfo, 2, GPU_FLOAT, 3); // v2=normal

	// Create the VBO
	vbo_data = linearAlloc(sizeof(model_vertices));
	memcpy(vbo_data, model_vertices, sizeof(model_vertices));

	// Configure buffers
	C3D_BufInfo* bufInfo = C3D_GetBufInfo();
	BufInfo_Init(bufInfo);
	BufInfo_Add(bufInfo, vbo_data, sizeof(vertex), 3, 0x210);

	// Use the vertex color (PRIMARY_COLOR) directly — no texture
	C3D_TexEnv* env = C3D_GetTexEnv(0);
	C3D_TexEnvInit(env);
	C3D_TexEnvSrc(env, C3D_Both, GPU_PRIMARY_COLOR, 0, 0);
	C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);
}

// Projection is passed in so the same draw call works for both eyes
static void sceneRender(C3D_Mtx* proj)
{
	// Build modelView: rotate around model origin, then apply camera translation
	C3D_Mtx modelView;
	Mtx_Identity(&modelView);
	Mtx_Translate(&modelView, camX, 0.0f, camZ, true);
	Mtx_RotateX(&modelView, angleX, true);
	Mtx_RotateY(&modelView, angleY, true);

	// Update uniforms
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLoc_projection, proj);
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLoc_modelView,  &modelView);
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLoc_material,   &material);
	C3D_FVUnifSet(GPU_VERTEX_SHADER, uLoc_lightVec,     0.0f, 0.0f, -1.0f, 0.0f);
	C3D_FVUnifSet(GPU_VERTEX_SHADER, uLoc_lightHalfVec, 0.0f, 0.0f, -1.0f, 0.0f);
	C3D_FVUnifSet(GPU_VERTEX_SHADER, uLoc_lightClr,     1.0f, 1.0f,  1.0f, 1.0f);

	// Draw the VBO
	C3D_DrawArrays(GPU_TRIANGLES, 0, model_vertex_count);
}

static void sceneExit(void)
{
	linearFree(vbo_data);
	shaderProgramFree(&program);
	DVLB_Free(vshader_dvlb);
}

int main()
{
	// Initialize graphics — gfxSet3D enables the parallax barrier
	gfxInitDefault();
	gfxSet3D(true);
	C3D_Init(C3D_DEFAULT_CMDBUF_SIZE);

	// Two render targets at 2x resolution (480x800) — one per eye.
	// The transfer hardware downscales to 240x400, giving 4xSSAA on both eyes.
	C3D_RenderTarget* targetLeft  = C3D_RenderTargetCreate(480, 800, GPU_RB_RGBA8, GPU_RB_DEPTH24_STENCIL8);
	C3D_RenderTarget* targetRight = C3D_RenderTargetCreate(480, 800, GPU_RB_RGBA8, GPU_RB_DEPTH24_STENCIL8);
	C3D_RenderTargetSetOutput(targetLeft,  GFX_TOP, GFX_LEFT,  DISPLAY_TRANSFER_FLAGS);
	C3D_RenderTargetSetOutput(targetRight, GFX_TOP, GFX_RIGHT, DISPLAY_TRANSFER_FLAGS);

	sceneInit();

	while (aptMainLoop())
	{
		hidScanInput();

		u32 kDown = hidKeysDown();
		u32 kHeld = hidKeysHeld();

		if (kDown & KEY_START)
			break;

		// R — begin animated reset (pressing again during animation re-triggers it)
		if (kDown & KEY_R)
			resetting = true;

		if (resetting) {
			// Ease-out lerp toward defaults — circle pad suspended so drift
			// doesn't prevent the angles from converging to zero
			camZ   += (CAM_Z_DEFAULT - camZ)  * RESET_SPEED;
			camX   += (CAM_X_DEFAULT - camX)  * RESET_SPEED;
			angleX += (0.0f - angleX)         * RESET_SPEED;
			angleY += (0.0f - angleY)         * RESET_SPEED;

			// Snap and finish when close enough on all axes
			if (fabsf(camZ - CAM_Z_DEFAULT) < RESET_EPSILON &&
			    fabsf(camX - CAM_X_DEFAULT) < RESET_EPSILON &&
			    fabsf(angleX) < RESET_EPSILON &&
			    fabsf(angleY) < RESET_EPSILON) {
				camZ = CAM_Z_DEFAULT; camX = CAM_X_DEFAULT;
				angleX = 0.0f;        angleY = 0.0f;
				resetting = false;
			}
		} else {
			// Circle pad — rotate model
			circlePosition pos;
			hidCircleRead(&pos);
			angleY += pos.dx * 0.0003f;
			angleX -= pos.dy * 0.0003f; // negate so up=tilt-up

			// D-Pad — zoom (up/down) and pan (left/right)
			if (kHeld & KEY_DUP)    camZ = camZ + ZOOM_SPEED < CAM_Z_NEAR ? camZ + ZOOM_SPEED : CAM_Z_NEAR;
			if (kHeld & KEY_DDOWN)  camZ = camZ - ZOOM_SPEED > CAM_Z_FAR  ? camZ - ZOOM_SPEED : CAM_Z_FAR;
			if (kHeld & KEY_DLEFT)  camX += PAN_SPEED;  // camera left = model shifts right
			if (kHeld & KEY_DRIGHT) camX -= PAN_SPEED;  // camera right = model shifts left
		}

		// Read the 3D slider and compute per-eye projections
		float iod = osGet3DSliderState() * IOD_SCALE;

		C3D_Mtx projLeft, projRight;
		if (iod > 0.0f) {
			// Stereo: offset each eye's projection by ±iod around the convergence plane
			Mtx_PerspStereoTilt(&projLeft,  FOV, C3D_AspectRatioTop, NEAR_PLANE, FAR_PLANE, -iod, SCREEN_DEPTH, false);
			Mtx_PerspStereoTilt(&projRight, FOV, C3D_AspectRatioTop, NEAR_PLANE, FAR_PLANE, +iod, SCREEN_DEPTH, false);
		} else {
			// Slider at zero — mono render into left eye only
			Mtx_PerspTilt(&projLeft, FOV, C3D_AspectRatioTop, NEAR_PLANE, FAR_PLANE, false);
		}

		C3D_FrameBegin(C3D_FRAME_SYNCDRAW);
			// Left eye (always rendered)
			C3D_RenderTargetClear(targetLeft, C3D_CLEAR_ALL, CLEAR_COLOR, 0);
			C3D_FrameDrawOn(targetLeft);
			sceneRender(&projLeft);

			// Right eye (only when slider is up)
			if (iod > 0.0f) {
				C3D_RenderTargetClear(targetRight, C3D_CLEAR_ALL, CLEAR_COLOR, 0);
				C3D_FrameDrawOn(targetRight);
				sceneRender(&projRight);
			}
		C3D_FrameEnd(0);
	}

	sceneExit();
	C3D_Fini();
	gfxExit();
	return 0;
}
